# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20180121_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wall_app.User'),
            preserve_default=False,
        ),
    ]
